### ISSUE TITLE
Need for a centralised error handling

### ISSUE THREAD

**Issue by avinash-lala** [tech-lalaworld/nodeBoilerPlate#2]
Every API we write requires error handling. Most of the error pertain to general things like incorrect parameters while processing, authorisation failure, server errors, etc. There is a lot of redundacy in handling these similar-in-spirit errors that could be normalised if there was a centralised error handling to tackle most of the common error types. It would also separate the business logic from the program logic and make the codebase more maintainable.
I would like to work on this proposal.

**Comment by rohan-lala** [comment]
I agree completely. Its not just the APIs, its true for other micro services that we may have to run.

**Comment by avinash-lala** [comment]
Feature added in v2.0. Closed via #10
