### ISSUE TITLE
Should use response caching

### ISSUE THREAD

**Issue by amitk-shangariglobal** [tech-lalaworld/nodeBoilerPlate#3]
If i am requesting a resource and response comes . Again I am requesting same resource which is not updated yet by POST/PUT/DELETE request. So In these type of cases  we can use response caching for reducing our MongoDB effort.

**Comment by karthikeyan-lala** [comment]
@amitk-shangariglobal, we are implementing the server side caching by implementing the CDN and Nginx. 
And we can't cache the PUT, POST and DELETE request, since every time we need to give the updated values.
